<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ferret.ConnectorPlatform</AssemblyName>
    <RootNamespace>Ferret.ConnectorPlatform</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ferret.Core\Ferret.Core.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>
</Project>
