namespace Ferret.Core.Ai.Models;

/// <summary>Role of a participant in a chat conversation.</summary>
public enum ChatRole
{
    /// <summary>A system-level instruction that frames the conversation.</summary>
    System,

    /// <summary>A message from the human user.</summary>
    User,

    /// <summary>A message generated by the AI assistant.</summary>
    Assistant,
}
