<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AnalysisMode>All</AnalysisMode>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <RootNamespace>Ferret.Search</RootNamespace>
    <AssemblyName>Ferret.Search</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Ferret.Core/Ferret.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="../../.editorconfig" Link=".editorconfig" />
  </ItemGroup>

  <ItemGroup>
    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
      <_Parameter1>Ferret.Search.Tests</_Parameter1>
    </AssemblyAttribute>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>

</Project>
