<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>Ferret.Providers.OpenAi</AssemblyName>
    <RootNamespace>Ferret.Providers.OpenAi</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenAI" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Ferret.Providers.OpenAi.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ferret.Core\Ferret.Core.csproj" />
    <ProjectReference Include="..\Ferret.Configuration.AI\Ferret.Configuration.AI.csproj" />
  </ItemGroup>

</Project>
