<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>Ferret.Connectors.Filesystem</AssemblyName>
    <RootNamespace>Ferret.Connectors.Filesystem</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Ferret.Core\Ferret.Core.csproj" />
  </ItemGroup>
</Project>
